openapi: 3.0.1
info:
  title: getData2
  description: API Definition of getData2
  version: 1.0.0
servers:
- url: http://localhost:8290/getdata2
paths:
  /:
    get:
      responses:
        default:
          description: Default response
