openapi: 3.0.1
info:
  title: getData4
  description: API Definition of getData4
  version: 1.0.0
servers:
- url: http://localhost:8290/getdata4
paths:
  /:
    get:
      responses:
        default:
          description: Default response
