openapi: 3.0.1
info:
  title: getData
  description: API Definition of getData
  version: 1.0.0
servers:
- url: http://localhost:8290/getdata
paths:
  /:
    get:
      responses:
        default:
          description: Default response
